### ISSUE TITLE
do these fonts also work with the KISS ULTRA after renaming?

### ISSUE THREAD

**Issue by pixbalance** [vicewize/vicewizeosdfontset#4]
I tried to rename them for the KISS Ultra, but without success. Are these specific for BF or is there a way to use them with the KISS Ultra?

**Comment by vicewize** [comment]
Unfortunately I believe the KISS OSD has a different element structure and layout so it most def (prob) wont work. Ill look into making a fork compatible w KISS if I can find the documentation on the layout and whatnot. Thanks for the idea btw ill def look into it and thanks for using my font package. :-)
